### ISSUE TITLE
I am facing this issue on localhost kindly check this.

### ISSUE THREAD

**Issue by mzeeshan455** [Livijn/laravel-object-detection#1]
![image](https://user-images.githubusercontent.com/81167105/144825080-276cee4a-8dd0-469c-bb59-d48ba71f8e35.png)

I am facing this issue on localhost kindly check this.
Thanks

**Comment by Livijn** [comment]
That is because you are using Windows. You can try [following this](https://stackoverflow.com/a/52287511/5191800l) answer on StackOverflow.
