### ISSUE TITLE
its not working using PHP 7.4, is there any chance to it work this on PHP 7.4 ?? only work's on PHP 8 or >

### ISSUE THREAD

**Issue by kevinjose-DXG** [Livijn/laravel-object-detection#3]
Package livijn/laravel-object-detection has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - livijn/laravel-object-detection 1.0 requires php ^8.0 which does not match your installed version 7.4.29.

**Comment by Livijn** [comment]
Yes, it requires >=PHP 8.
