### ISSUE TITLE
The command "DEBUG_IMAGE=0 node D:\xampp\htdocs\test_project\vendor\livijn\laravel-object-detection\src/../scripts/index.js images (1).jpg" failed. Exit Code: 1(General error) Working directory:

### ISSUE THREAD

**Issue by kevinjose-DXG** [Livijn/laravel-object-detection#4]
I am getting this error while I am uploading an image from my Laravel blade.... can i get a solution for this ?as i am new to Laravel. thanks in advance...

**Comment by Livijn** [comment]
Sorry, you need to get help from forums.
